run:
  timeout: 5m
  issues-exit-code: 2
  modules-download-mode: readonly
  allow-parallel-runners: false

output:
  format: colored-line-number,github-actions
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosmopolitan
    - gosimple
    - govet
    - ineffassign
    - interfacebloat
    - lll
    - misspell
    - nakedret
    - nilerr
    - noctx
    - paralleltest
    - perfsprint
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/tomjowitt/gotidal

  exhaustive:
    check:
      - switch
      - map
    default-signifies-exhaustive: true

  varnamelen:
    ignore-names:
      - err
      - tt
